# アプリケーション名
app_name = "kinmuhyo"
# ログレベル
log_level = "your logLevel"
log_path = "your logpath"

# client
[client]
    [client.rds]
    dialect = "yourDBName"
    dsn = "yourDBDSN"
    idle_conn = 10
    max_conn = 10
    debug = true
    